version: '3.1'

services:
  db:
    container_name: plapy_prod
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: plapyDev
      POSTGRES_DB: plapy_production_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: