# Use an official PostgreSQL runtime as a parent image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER your_username
ENV POSTGRES_PASSWORD your_password
ENV POSTGRES_DB plapy_production

# Copy the schema file into the container
COPY schema.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432
